// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $blog_name_ from "./routes/blog/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/blog.tsx": $blog,
    "./routes/blog/[name].tsx": $blog_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
